
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

# lovelace:
# mode: yaml        

discovery:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://hass.malt.no

hacs:
  token: 74df8289984328a4ed7f965a525e211bb0f4ed69

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config_glob:
    "sensor.*_exporting*":
      ignored: true
    "sensor.*_sourcenodeid*":
      ignored: true

# Text to speech
tts:
  - platform: google_translate

recorder:
  db_url: !secret recorder_db_url

sensor:
  - platform: yr
    name: Yr
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
  - platform: nut
    name: ups
    host: 192.168.71.3
    resources:
      - ups.load
      - ups.status
      - battery.charge
      - battery.runtime
      - input.voltage
      - output.voltage
  - platform: plex

ios:

media_player:
  - platform: spotify
    client_id: c57f686ac1e74b2d92e728c03fd20c14
    client_secret: c1bf839379f844d0891d8601c4431d1c
  - platform: braviatv
    host: 192.168.71.134

tahoma: !secret tahoma_config

verisure: !secret verisure_config

netatmo: !secret netatmo_config

mqtt: !secret mqtt_config

mqtt_eventstream:
  publish_topic: '/homeassistant/eventstream'

light: !include lights.yaml
input_select: !include input_select.yaml
group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automation/
script: !include_dir_named scripts/

