homeassistant:
  name: SD60
  latitude: 59.911525
  longitude: 10.831530
  elevation: 120
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
frontend:

config:

http:
  api_password: !secret http_password
  base_url: https://hass.malt.no
  cors_allowed_origins:
    - https://sunscreen.malt.no
    - https://hass.malt.no
    - https://www.malt.no
    - http://localhost:3000

panel_iframe:
  router:
    title: 'micronuke'
    url: 'http://192.168.71.1/'
    icon: 'mdi:router-wireless'
  grafana:
    title: 'grafana'
    url: 'https://hass.malt.no/grafana/'
    icon: 'mdi:television-guide'

hassio:

# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

discovery:
  # ignore:
  #   - songpal

ios:

homekit:
  auto_start: false
  filter:
    exclude_domains:
      - binary_sensor
    exclude_entities:
      - light.hue_camera
  entity_config:
    lock.front_door_lock_locked:
      code: 1910

conversation:

map:

sun:

# recorder:
#  purge_keep_days: 10

        # history:
        # exclude:
        # domains:
        # - automation
        # - weblink
        # - updater

# Weather prediction
sensor:
  - platform: yr
    name: Yr.no
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: load_5m
      - type: processor_use
      - type: memory_use_percent
#  - platform: ruter
#    stop_id: 3011510

# Text to speech
tts:
  - platform: google

## Cloud
cloud:

hue:
  bridges:
    - host: 192.168.71.22

media_player:
  - platform: braviatv
    host: 192.168.71.134

# Example configuration.yaml entry
netatmo:
  api_key: !secret netatmo_apikey
  secret_key: !secret netatmo_secret_key
  username: thomas@malt.no
  password: !secret netatmo_password

verisure: !secret verisure_config

zwave:
  usb_path: /dev/ttyACM0
  network_key: "0x1A, 0x08, 0x47, 0x04, 0x07, 0x0A, 0x0B, 0x0C, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10"

mqtt: !secret mqtt_config

mqtt_eventstream:
  publish_topic: '/homeassistant/eventstream'

mqtt_statestream:
  base_topic: '/homeassistant/statestream'
  publish_attributes: false

light:
  - platform: mqtt_json
    name: "ESP32 Development"
    state_topic: "/ledshelf/light/state"
    command_topic: "/ledshelf/light/set"
    availability_topic: "/ledshelf/status"
    effect: true
    effect_list:
      - none
      - BPM
      - Confetti
      - Glitter Rainbow
      - Juggle
      - Rainbow
      - Sinelon
    retain: false
    payload_available: Online
    payload_not_available: Disconnected
    rgb: true
    hs: true
    white_value: false
    color_temp: true
    brightness: true
    qos: 0

switch:
  - platform: mqtt
    name: "Martha Heater Switch"
    state_topic: /zipato/attributes/d956bf74-dc47-4d3c-8d4f-37cccb0bf3b3/value
    command_topic: /zipato/request/attributes/d956bf74-dc47-4d3c-8d4f-37cccb0bf3b3/textValue
    value_template: '{{value_json.value}}'
    payload_on: true
    payload_off: false
    optimistic: false
    qos: 2
    retain: true
  - platform: mqtt
    name: "TV Heater Switch"
    state_topic: /zipato/attributes/490dca82-8b56-4e20-834a-ec0e54975711/value
    command_topic: /zipato/request/attributes/490dca82-8b56-4e20-834a-ec0e54975711/textValue
    value_template: '{{value_json.value}}'
    payload_on: true
    payload_off: false
    optimistic: false
    qos: 2
    retain: true

input_select:
  sd60_mode:
    name: "SD60 Modes"
    options:
      - Morning
      - Day
      - Evening
      - Night
      - Party
    initial: Day
  home_away:
    name: "Home or Away"
    options:
      - Home
      - Away
      - Vacation
    initial: Home

group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automation/
script: !include_dir_named scripts/
