# Configuration file for Home Assistant.
# It is provided in case snippets and bits can be useful for others getting
# started, the same way other peoples repositories were useful to me.
#
# Copyright Thomas Malt 2016-2018
# License: Creative Commons BY-SA

homeassistant:
  name: SD60
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 120
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

frontend:
config:
http:
  api_password: !secret http_password
  base_url: https://hass.malt.no
  cors_allowed_origins:
    - https://sunscreen.malt.no
    - https://hass.malt.no
    - https://www.malt.no
    - http://localhost:3000

panel_iframe:
  router:
    title: 'micronuke'
    url:  !secret router_url
    icon: 'mdi:router-wireless'
  grafana:
    title: 'grafana'
    url: !secret grafana_url
    icon: 'mdi:television-guide'

hassio:

# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  include_used_components: true

discovery:
ios:

homekit:
  auto_start: false
  filter:
    exclude_domains:
      - binary_sensor
    exclude_entities:
      - light.hue_camera

conversation:
map:
sun:

# Weather prediction
sensor:
  - platform: yr
    name: Yr.no
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: load_5m
      - type: processor_use
      - type: memory_use_percent
  - platform: ruter
    stop_id: 3011510

# Text to speech
tts:
  - platform: google

## Cloud
cloud:

hue:
  bridges:
    - host: !secret hue_bridge

media_player:
  - platform: braviatv
    host: !secret tv_ip

netatmo: !secret netatmo_config
verisure: !secret verisure_config
mqtt: !secret mqtt_config

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key

mqtt_eventstream:
  publish_topic: '/homeassistant/eventstream'

mqtt_statestream:
  base_topic: '/homeassistant/statestream'
  publish_attributes: true

light: !include lights.yaml

switch:
  - platform: mqtt
    name: "Martha Heater Switch"
    state_topic: /zipato/attributes/d956bf74-dc47-4d3c-8d4f-37cccb0bf3b3/value
    command_topic: /zipato/request/attributes/d956bf74-dc47-4d3c-8d4f-37cccb0bf3b3/textValue
    value_template: '{{value_json.value}}'
    payload_on: true
    payload_off: false
    optimistic: false
    qos: 2
    retain: true
  - platform: mqtt
    name: "TV Heater Switch"
    state_topic: /zipato/attributes/490dca82-8b56-4e20-834a-ec0e54975711/value
    command_topic: /zipato/request/attributes/490dca82-8b56-4e20-834a-ec0e54975711/textValue
    value_template: '{{value_json.value}}'
    payload_on: true
    payload_off: false
    optimistic: false
    qos: 2
    retain: true

input_select:
  sd60_mode:
    name: "SD60 Modes"
    options:
      - Morning
      - Day
      - Evening
      - Night
      - Party
    initial: Day
  home_away:
    name: "Home or Away"
    options:
      - Home
      - Away
      - Vacation
    initial: Home

group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automation/
script: !include_dir_named scripts/
