version: "2"

services:
    home-assistant:
        image: homeassistant/home-assistant:stable
        container_name: "ha_core"
        restart: "unless-stopped"
        volumes:
            - ./config:/config
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0
            - /dev/ttyACM0:/dev/ttyACM0
        environment:
            TZ: "Europe/Oslo"
        network_mode: host
        depends_on:
            - postgres
    postgres:
        image: postgres
        container_name: "ha_db"
        restart: "unless-stopped"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "hass"
            POSTGRES_PASSWORD: "ohTeiqu3ohkey4giekae2suuloh2icei"
            POSTGRES_DB: "hass"
        volumes:
            - ha_db_data:/var/lib/postgresql/data

volumes:
    ha_db_data:
        driver: local
