
- platform: mqtt
  schema: json
  name: "Marthas Bookshelf All"
  state_topic: "/ledshelf/light/state"
  command_topic: "/ledshelf/light/set"
  availability_topic: "/ledshelf/status"
  effect: true
  effect_list:
    - none
    - BPM
    - Confetti
    - Glitter Rainbow
    - Juggle
    - Rainbow
    - RainbowByShelf
    - Sinelon
  retain: false
  payload_available: Online
  payload_not_available: Disconnected
  rgb: true
  hs: true
  white_value: false
  color_temp: true
  brightness: true
  qos: 0

- platform: mqtt
  schema: json
  name: "Marthas Bookshelf Top Left"
  state_topic: "/leddev/topleft/state"
  command_topic: "/leddev/topleft/set"
  availability_topic: "/leddev/status"
  effect: true
  effect_list:
    - none
    - BPM
    - Confetti
    - Glitter Rainbow
    - Juggle
    - Rainbow
    - Sinelon
  retain: false
  payload_available: Online
  payload_not_available: Disconnected
  rgb: true
  hs: true
  white_value: false
  color_temp: true
  brightness: true
  qos: 0

- platform: mqtt
  schema: json
  name: "Marthas Bookshelf Top Center"
  state_topic: "/leddev/topcenter/state"
  command_topic: "/leddev/topcenter/set"
  availability_topic: "/leddev/status"
  effect: true
  effect_list:
    - none
    - BPM
    - Confetti
    - Glitter Rainbow
    - Juggle
    - Rainbow
    - Sinelon
  retain: false
  payload_available: Online
  payload_not_available: Disconnected
  rgb: true
  hs: true
  white_value: false
  color_temp: true
  brightness: true
  qos: 0

- platform: mqtt
  schema: json
  name: "Marthas Bookshelf Top Right"
  state_topic: "/leddev/topright/state"
  command_topic: "/leddev/topright/set"
  availability_topic: "/leddev/status"
  effect: true
  effect_list:
    - none
    - BPM
    - Confetti
    - Glitter Rainbow
    - Juggle
    - Rainbow
    - Sinelon
  retain: false
  payload_available: Online
  payload_not_available: Disconnected
  rgb: true
  hs: true
  white_value: false
  color_temp: true
  brightness: true
  qos: 0

- platform: mqtt
  schema: json
  name: "Development Test"
  state_topic: "/leddev/light/state"
  command_topic: "/leddev/light/set"
  availability_topic: "/leddev/status"
  effect: true
  effect_list:
    - none
    - BPM
    - Confetti
    - Glitter Rainbow
    - Juggle
    - Rainbow
    - RainbowByShelf
    - Sinelon
  retain: false
  payload_available: Online
  payload_not_available: Disconnected
  rgb: true
  hs: true
  white_value: false
  color_temp: true
  brightness: true
  qos: 0
