---
# ---------------------------------------------------------------------------
# Downstairs motion
# ---------------------------------------------------------------------------
- alias: "Downstairs Motion - Set state to Home"
  trigger:
    - platform: state
      entity_id: sensor.downstairs_sensor_burglar
      from: "0"
      to: "8"
  condition:
    condition: state
    entity_id: input_select.home_away
    state: Away
  action:
    - service: notify.ios_tmobil_x
      data:
        title: "Downstairs motion when away"
        message: "Setting state to Home."
    - service: input_select.select_option
      entity_id: input_select.home_away
      data:
        option: Home

# ---------------------------------------------------------------------------
# Downstairs motion - Turning on lights
# ---------------------------------------------------------------------------
- alias: "Downstairs Motion - Turning on Lights"
  trigger:
    - platform: state
      entity_id: sensor.dining_room_burglar
      to: "8"
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state('input_select.dining_room_lights', 'Off') }}"
      - condition: or
        conditions:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
  action:
    - service: script.downstairs_bright
    - service: notify.ios_tmobil_x
      data:
        title: "Downstairs Motion after sunset"
        message: >
          Downstairs motion detected. Luminance is
          {{ states.sensor.downstairs_sensor_luminance.state }}
          lux, so turning on lights.

# ---------------------------------------------------------------------------
# Downstairs Motion - No Motion at Night
# ---------------------------------------------------------------------------
- alias: "Downstairs Motion - No Motion at Night"
  trigger:
    - platform: state
      entity_id: sensor.dining_room_burglar
      from: "8"
      to: "0"
  condition:
    condition: state
    entity_id: input_select.sd60_mode
    state: Night
  action:
    - service: notify.ios_tmobil_x
      data:
        title: "Downstairs no Motion at night"
        message: "No Motion triggered. And it's night."
    - service: script.downstairs_off
