# ---------------------------------------------------------------------------
# Dining room heating
# ---------------------------------------------------------------------------
- alias: 'Dining room Heating Morning On'
  trigger:
    platform: time
    at: '04:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.home_away
        state: Home
      - condition: numeric_state
        entity_id: sensor.downstairs_sensor_temperature
        below: 23
  action:
    - service: climate.set_temperature 
      entity_id: climate.dining_room_heating_heating
      data:
        temperature: 20
    - service: notify.ios_tmobil_x
      data:
        title: "Dining Room Heating"
        message: >
          Dining Room Heating ON. Current temperature -> 
          {{ sensor.dining_room_heating_temperature }}
          °C, Goal -> 20°C

- alias: 'Dining Room Heating Morning Off'
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: climate.set_temperature
      entity_id: climate.dining_room_heating_heating
      data: 
        temperature: 10
    - service: notify.ios_tmobil_x
      data:
        title: "Dining Room Heating"
        message: > 
          Dining Room Heating OFF. Current temperature -> 
          {{ sensor.dining_room_heating_temperature }}
          °C, Goal -> 10°C

- alias: 'Dining Room Heating Evening On'
  trigger:
    platform: time
    at: '15:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.home_away
        state: Home
      - condition: numeric_state
        entity_id: sensor.downstairs_sensor_temperature
        below: 23
  action:
    - service: climate.set_temperature 
      entity_id: climate.dining_room_heating_heating
      data:
        temperature: 20
    - service: notify.ios_tmobil_x
      data:
        title: "Dining Room Heating"
        message: > 
          Dining Room Heating ON. Current temperature -> 
          {{ sensor.dining_room_heating_temperature }}
          °C, Goal -> 20°C

- alias: 'Dining Room Heating Evening Off'
  trigger:
    - platform: time
      at: '22:00:00'
  action:
    - service: climate.set_temperature
      entity_id: climate.dining_room_heating_heating
      data: 
        temperature: 10
    - service: notify.ios_tmobil_x
      data:
        title: "Dining Room Heating"
        message: >
          Dining Room Heating OFF. Current temperature -> 
          {{ sensor.dining_room_heating_temperature }}
          °C, Goal -> 10°C
