- alias: 'Homeassistant is shutting down'
  trigger:
    platform: homeassistant
    # Event can also be 'shutdown'
    event: shutdown
  action:
    - service: notify.ios_tmobil_x
      data:
        title: 'Home Assistant is shutting down'
        message: >
          Got homeassistant shutdown event. 
