- alias: 'Kitchen - Coffee Maker - Start timer on power'
  trigger:
    - platform: numeric_state
      entity_id: sensor.coffee_switch_power
      above: 20
  action:
    - service: timer.start
      entity_id: timer.coffee
      data:
        duration: '00:30:00'
    - service: notify.ios_tmobil_x
      data:
        title: "Coffee timer started"
        message: "Duration is 30 minutes"

- alias: 'Kitchen - Coffee Maker - Turn off switch on timer'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.coffee
  action:
    - service: notify.ios_tmobil_x
      data:
        title: "Coffee timer finished"
        message: "Turning off Coffee Switch"
    - service: switch.turn_off
      entity_id: switch.coffee
 
- alias: 'Kitchen - Coffee Maker - Cancel Timer if off'
  trigger:
    - platform: numeric_state
      entity_id: sensor.coffee_switch_power
      below: 1
  action:
    - service: timer.cancel
      entity_id: timer.coffee
    - service: notify.ios_tmobil_x
      data:
        title: "Coffee Timer Cancelled"
        message: "Coffee Maker was turned off"

- alias: 'Kitchen - Coffee Maker State - Off'
  trigger:
    - platform: numeric_state
      entity_id: sensor.coffee_switch_power
      below: 1
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.coffee_maker_state
        option: "Off"

- alias: 'Kitchen - Coffee Maker State - Heating'
  trigger:
    - platform: numeric_state
      entity_id: sensor.coffee_switch_power
      below: 1200
      above: 20
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.coffee_maker_state
        option: "Heating"
 
- alias: 'Kitchen - Coffee Maker State - Brewing'
  trigger:
    - platform: numeric_state
      entity_id: sensor.coffee_switch_power
      above: 1200
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.coffee_maker_state
        option: "Brewing"
