- alias: 'Upstairs Bathroom is heating on'
  trigger:
    platform: event
    event_type: zwave.node_event
    event_data:
      entity_id: zwave.upstairs_bathroom_heating
      basic_level: 255
  action:
    service: notify.ios_tmobil_x
    data:
      title: 'Upstairs Bathroom'
      message: 'Heating is ON'
 
- alias: 'Upstairs Bathroom is heating off'
  trigger:
     platform: event
     event_type: zwave.node_event
     event_data:
       entity_id: zwave.upstairs_bathroom_heating
       basic_level: 0
  action:
    - service: notify.ios_tmobil_x
      data:
        title: 'Upstairs Bathroom'
        message: 'Heating is OFF'