# This script turns all lights downstairs dimmed and cozy!
alias: Downstairs Dimmed
sequence:
  - service: light.turn_on
    entity_id:
      - light.downstairs_chandelier
      - light.downstairs_kitchen_spots
    data:
      brightness: 50
      transition: 4
  - service: light.turn_on
    entity_id: light.downstairs_couch_spots
    data:
      brightness: 60
      transition: 4
  - service: light.turn_on
    entity_id: light.downstairs_carpet_spots
    data:
      brightness: 20
      transition: 4
      #  - service: light.turn_on
      # entity_id: light.globe
      # data:
      # brightness: 168
      # transition: 2
      # kelvin: 2300
  - service: light.turn_on
    entity_id:
      - light.paper
      - light.downstairs_couch_lights
    data:
      brightness: 128
      transition: 4
      kelvin: 2300
  - service: light.turn_on
    entity_id: light.kitchen_counter
    data:
      brightness: 255
      transition: 4
      kelvin: 2700
  - service: input_select.select_option
    entity_id: input_select.dining_room_lights
    data:
      option: "Dimmed"
