# This script turns all lights downstairs on bright and shiny
alias: Downstairs Bright
sequence:
  - service: light.turn_on
    entity_id: light.downstairs_all_white_light
    data:
      brightness: 250
  - service: light.turn_on
    entity_id: light.downstairs_all_zha_group_0x0010
    data:
      brightness: 255
      color_temp: 360
  - service: light.turn_on
    entity_id: light.downstairs_bookshelf_zha_group_0x000d
    data:
      color_temp: 360
      brightness: 255

  - service: input_select.select_option
    entity_id: input_select.dining_room_lights
    data:
      option: "Bright"
