alias: Downstairs - All lights on bright
sequence:
  - service: input_select.select_option
    data:
      entity_id: input_select.dining_room_lights
      option: "Bright"
  - service: light.turn_on
    entity_id:
      - light.downstairs_all_zha_group_0x0010
      - light.downstairs_all_white_light
    data:
      brightness: 255
  - delay: 1
  - service: light.turn_on
    entity_id: light.downstairs_all_zha_group_0x0010
    data:
      color_temp: 360
