alias: Downstairs - All lights off
sequence:
  - service: input_select.select_option
    entity_id:
      - input_select.dining_room_lights
    data:
      option: "Off"
  - service: light.turn_off
    entity_id:
      - light.downstairs_all_white_light
      - light.downstairs_all_zha_group_0x0010
