alias: Downstairs - All lights on bright
sequence:
  - service: light.turn_on
    entity_id: light.bokhylle_nede
    data:
      transition: 2
      color_temp: 350
      brightness: 255
  - service: light.turn_on
    entity_id: light.downstairs_all_white_lights
    data:
      brightness: 255
      transition: 2
  - service: light.turn_on
    entity_id: light.downstairs_all_rgb_lights
    data:
      brightness: 255
      kelvin: 2700
      transition: 2
