# - service: input_select.select_option
#   entity_id: input_select.sd60_mode
#   data:
#     option: "Morning"

alias: TV Bright
sequence:
  - service: light.turn_on
    target:
      entity_id:
        - light.tv_area_zha_group_0x000b
        - light.tv_room
    data:
      brightness: 255
      color_temp: 370
  - service: input_select.select_option
    data:
      entity_id: input_select.tv_lights
      option: "Bright"
