alias: TV Dimmed
sequence:
  - service: light.turn_on
    entity_id:
      - light.tv_bookshelf_lights
    data:
      brightness: 104
      transition: 1
      kelvin: 2000
  - service: light.turn_on
    entity_id:
      - light.entrance_lights
      - light.stairs_lights
      - light.picture_wall
      - light.tv_couch_lights
      - light.upstairs_bathroom_hallway_light
    data:
      brightness: 80
      kelvin: 2000
      transition: 1
