alias: TV Dimmed
sequence:
  - service: input_select.select_option
    data:
      entity_id: input_select.tv_lights
      option: "Dimmed"
  - service: light.turn_on
    entity_id:
      - light.tv_bookshelf_zha_group_0x0007
      - light.tv_lights_zha_group_0x0008
    data:
      brightness: 104
  - service: light.turn_on
    entity_id:
      - light.entrance_zha_group_0x0005
      - light.stairs_zha_group_0x0006
      - light.picture_wall_zha_group_0x000a
      - light.tv_couch_zha_group_0x0009
    data:
      brightness: 80
  - delay: 1
  - service: light.turn_on
    entity_id:
      - light.tv_area_zha_group_0x000b
    data:
      color_temp: 450
