alias: TV Medium Bright
sequence:
  - service: input_select.select_option
    data:
      entity_id: input_select.tv_lights
      option: "Medium"
  - service: light.turn_on
    entity_id:
      - light.tv_room
    data:
      brightness: 180
      color_temp: 400
  - service: light.turn_on
    entity_id:
      - light.tv_couch_zha_group_0x0009
      - light.picture_wall_zha_group_0x000a
      - light.entrance_zha_group_0x0005
      - light.stairs_zha_group_0x0006
    data:
      brightness: 168
  - delay: 1
  - service: light.turn_on
    entity_id:
      - light.tv_area_zha_group_0x000b
    data:
      color_temp: 400
