alias: TV Off
sequence:
  - service: light.turn_off
    target:
      entity_id: 
        - light.tv_area_zha_group_0x000b
        - light.tv_room
    data:
      transition: 1
  - service: light.turn_on
    target:
      entity_id:
        - light.upstairs_bathroom_hallway2
    data:
      brightness: 20
      kelvin: 2000
      transition: 1
  - service: input_select.select_option
    data:
      entity_id: input_select.tv_lights
      option: "Off"
