- id: "1639313561543"
  alias: Downstairs Bathroom Motion
  description: "Turn lights on when motion detected in downstairs bathroom"
  trigger:
    - platform: state
      entity_id: binary_sensor.multisensor_e_downstairs_bathroom_home_security_motion_detection
      to: "on"
  condition: []
  action:
    - service: light.turn_on
      target:
        entity_id: light.downstairs_bathroom_dimmer
      data:
        brightness: 200
  mode: single
