- id: "1639313561542"
  alias: Downstairs Bathroom Motion
  description: "Turn lights on when motion detected in downstairs bathroom"
  trigger:
    - platform: state
      entity_id: binary_sensor.multisensor_e_home_security_motion_detection
      from: "off"
      to: "on"
  condition: []
  action:
    - service: light.turn_on
      target:
        entity_id: light.downstairs_bathroom_dimmer
      data:
        brightness: 255
  mode: single

- id: "1639313561542"
  alias: Downstairs Bathroom Motion Off
  description: "Turn lights 20 minutes after motion detected in downstairs bathroom"
  trigger:
    - platform: state
      entity_id: binary_sensor.multisensor_e_home_security_motion_detection
      from: "on"
      to: "off"
      for: "00:20:00"
  condition: []
  action:
    - service: light.turn_off
      target:
        entity_id: light.downstairs_bathroom_dimmer
      data:
        brightness: 0
  mode: single
