- id: "1638908262867"
  alias: Electricity above 8000 Watts
  description:
    When electricity consumption is above 8kW water heater should be turned
    off.
  trigger:
    - platform: numeric_state
      entity_id: sensor.power_simon_darres_vei_60
      above: 8000
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.water_heater
    - service: notify.devices_to_notify
      data:
        title: Electricity usage is above 8000 W
        message: Turning off water heater
  mode: single

- id: "1638908262868"
  alias: Electricity above 5kW
  description:
    When electricity consumption is above 5kW some stuff should be turned
    off.
  trigger:
    - platform: time_pattern
      minutes: "/2"
    - platform: numeric_state
      entity_id: sensor.power_simon_darres_vei_60
      above: 5000
  condition:
    - condition: numeric_state
      entity_id: sensor.power_simon_darres_vei_60
      above: 5000
  action:
    - service: climate.set_temperature
      target:
        entity_id: >
          {% set ns = namespace(heater="") %}
          {% for heater in expand('group.heating') if state_attr(heater.entity_id, 'temperature') > 16 %}
            {% set ns.heater = heater.entity_id %}
          {% endfor %}
          {{ ns.heater }}

      data:
        temperature: 16
  mode: single

- id: "1638908262869"
  alias: Electricity below 2kW
  description:
    When electricity consumption is below 3kW and price level is normal or cheap heating can be turned
    on.
  trigger:
    - platform: time_pattern
      minutes: "/2"
    - platform: numeric_state
      entity_id: sensor.power_simon_darres_vei_60
      below: 3000
  condition:
    - condition: numeric_state
      entity_id: sensor.power_simon_darres_vei_60
      below: 3000
    - condition: state
      entity_id: sensor.electricity_price
      attribute: price_level
      state:
        - NORMAL
        - CHEAP
        - VERY_CHEAP
  action:
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_living_room
      data:
        temperature: 19
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_downstairs_bathroom
      data:
        temperature: 24
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_upstairs_bathroom
      data:
        temperature: 26
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_utility_room
      data:
        temperature: 22
    - service: switch.turn_on
      target:
        entity_id: switch.water_heater
