# ---------------------------------------------------------------------
# Electricity usage for floor heating dynamic threshold
# ---------------------------------------------------------------------
- id: "1638908262868"
  alias: Electricity usage Floor Heating dynamic threshold
  description:
    When electricity consumption is above dynamic threshold floor heating
    should be turned off in prioritized order.
  trigger:
    - platform: time_pattern
      minutes: "/1"
    - platform: numeric_state
      entity_id: sensor.sd60_power
      above: sensor.sd60_power_budget
  condition:
    - condition: numeric_state
      entity_id: sensor.sd60_power
      above: sensor.sd60_power_budget
  action:
    - service: climate.set_temperature
      target:
        entity_id: >
          {% set ns = namespace(heater="") %}
          {% for heater in expand('group.heating') if state_attr(heater.entity_id, 'temperature') >= state_attr(heater.entity_id, 'current_temperature')|float %}
            {% set ns.heater = heater.entity_id %}
          {% endfor %}
          {{ ns.heater }}

      data:
        temperature: >
          {{ states('input_number.default_minimum_temperature')|float }}
  mode: single

# ---------------------------------------------------------------------
# Electricity usage below low threshold
# ---------------------------------------------------------------------
- id: "1638908262869"
  alias: Electricity usage Floor Heating below low threshold
  description:
    When electricity consumption is below 3kW and price level is normal or cheap heating can be turned
    on.
  trigger:
    - platform: time_pattern
      minutes: "/1"
    - platform: numeric_state
      entity_id: sensor.sd60_power
      value_template: >
        {{ states('sensor.sd60_power')|int + 2000 }}
      below: sensor.sd60_power_budget
  condition:
    - condition: numeric_state
      entity_id: sensor.sd60_power
      value_template: >
        {{ states('sensor.sd60_power')|int + 2000 }}
      below: sensor.sd60_power_budget
    - condition: numeric_state
      entity_id: sensor.sd60_electricity_price_percentile
      below: input_number.electricity_price_percentile_limit
  action:
    - service: climate.set_temperature
      target:
        entity_id: >
          {% set ns = namespace(heater="") %}
          {% for heater in expand('group.heating')|reverse if state_attr(heater.entity_id, 'temperature') <= states('input_number.default_minimum_temperature')|float %}
            {% set ns.heater = heater.entity_id %}
          {% endfor %}
          {{ ns.heater }}
      data:
        temperature: >
          {% set ns = namespace(heater="") %}
          {% set temps = {
            'climate.heating_living_room': states('input_number.default_temp_living_room')|float, 
            'climate.heating_downstairs_bathroom': states('input_number.default_temp_downstairs_bathroom')|float,
            'climate.heating_upstairs_bathroom': states('input_number.default_temp_upstairs_bathroom')|float,
            'climate.heating_utility_room': states('input_number.default_temp_utility_room')|float
          } %}
          {% for heater in expand('group.heating')|reverse if state_attr(heater.entity_id, 'temperature') <= states('input_number.default_minimum_temperature')|float %}
            {% set ns.heater = heater.entity_id %}
            {% set ns.temp = temps[heater.entity_id] %}
          {% endfor %}
          {{ ns.temp }}

# ---------------------------------------------------------------------
# Water Heater - Electricity usage is above threshold
# ---------------------------------------------------------------------
- id: "1638908262867"
  alias: Electricity Water Heater above threshold
  description:
    When electricity consumption is above threshold water heater should be turned
    off.
  trigger:
    - platform: time_pattern
      minutes: "/5"
  condition:
    - condition: state
      entity_id: switch.water_heater
      state: "on"
    - condition: numeric_state
      entity_id: sensor.sd60_power
      above: sensor.sd60_power_budget
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.water_heater
    - service: notify.devices_to_notify
      data:
        title: Turning off water heater
        message: Electricity usage is above {{ states('sensor.sd60_power_budget')|int }} W
  mode: single

# ---------------------------------------------------------------------
# Water Heater - Electricity usage below low threshold
# ---------------------------------------------------------------------
- id: "1638908262872"
  alias: Electricity Water Heater below threshold
  description:
    When electricity consumption is below threshold and price level is normal or cheap heating can be turned
    on.
  trigger:
    - platform: time_pattern
      minutes: "/5"
    - platform: numeric_state
      entity_id: sensor.sd60_power
      below: input_number.lower_watt_threshold
  condition:
    - condition: numeric_state
      entity_id: sensor.sd60_electricity_price
      below: sensor.sd60_waterheater_limit_price
    - condition: state
      entity_id: switch.water_heater
      state: "off"
    - condition: numeric_state
      entity_id: sensor.sd60_power
      value_template: >
        {{ states('sensor.sd60_power')|int + 3200 }}
      below: sensor.sd60_power_budget
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.water_heater
