# ---------------------------------------------------------------------
# Electricity - Floor Heating Exceeding Power Budget
# ---------------------------------------------------------------------
- id: "1638908262868"
  alias: Electricity - Floor Heating Exceeding Power Budget
  description: When electricity consumption exceeds power budget floor heating
    should be turned off in prioritized order.
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    or:
      - condition: numeric_state
        entity_id: sensor.heating_power_budget_delta
        below: 0
      - condition: numeric_state
        entity_id: sensor.sd60_power_budget
        below: 2000
  action:
    - alias: "choose if there is a heater"
      choose:
        - conditions: "{{ state_attr('group.heating', 'entity_id') | select('is_state', 'heat') | list | last is defined }}"
          sequence:
            - service: climate.set_hvac_mode
              target:
                entity_id: >
                  {{ state_attr('group.heating', 'entity_id') | select('is_state', 'heat') | list | last }}
              data:
                hvac_mode: "off"

# ---------------------------------------------------------------------
# Electricity usage below low threshold
# ---------------------------------------------------------------------
#    - condition: numeric_state
#      entity_id: sensor.sd60_electricity_price_percentile
#      below: input_number.electricity_price_percentile_limit
- id: "1638908262869"
  alias: Electricity - Floor Heating Within Power Budget
  description: When floor heating can be turned on.
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: numeric_state
      entity_id: sensor.sd60_power_budget
      above: 2200
    - condition: numeric_state
      entity_id: sensor.heating_power_budget_delta
      above: 1000
  action:
    - alias: "choose if there is a heater"
      choose:
        - conditions: "{{ state_attr('group.heating', 'entity_id') | select('is_state', 'off') | list | first is defined }}"
          sequence: 
            - service: climate.set_hvac_mode
              target:
                entity_id: >
                  {{ state_attr('group.heating', 'entity_id') | select('is_state', 'off') | list | first }}
              data:
                hvac_mode: "heat"

# ---------------------------------------------------------------------
# Water Heater - Electricity usage is above threshold
# ---------------------------------------------------------------------
- id: "1638908262867"
  alias: Electricity - Water Heater exceeding power budget
  description:
    When electricity consumption is above threshold water heater should be turned
    off.
  trigger:
    - platform: time_pattern
      minutes: "/1"
    - platform: numeric_state
      entity_id: sensor.sd60_power_budget
      below: 2000
  condition:
    - condition: state
      entity_id: switch.water_heater
      state: "on"
    - condition: numeric_state
      entity_id: sensor.sd60_power_budget
      below: 2000
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.water_heater
    - service: notify.devices_to_notify
      data:
        title: Turning off water heater
        message: Electricity usage is above power budget {{ states('sensor.sd60_power_budget')|int }} W
  mode: single

# ---------------------------------------------------------------------
# Water Heater - Electricity usage below low threshold
# ---------------------------------------------------------------------
- id: "1638908262872"
  alias: Electricity - Water Heater within power budget
  description: When Water heater can be turned on
  trigger:
    - platform: time_pattern
      minutes: "/1"
    - platform: numeric_state
      entity_id: sensor.sd60_power_budget
      above: 3600
  condition:
    - condition: numeric_state
      entity_id: sensor.sd60_electricity_price
      below: sensor.sd60_waterheater_limit_price
    - condition: state
      entity_id: switch.water_heater
      state: "off"
    - condition: numeric_state
      entity_id: sensor.sd60_power_budget
      above: 3600
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.water_heater
