#
# Turn off floor heating when expensive
#
- id: "1638626031020"
  alias: "Pricing - Turn off floor heating when expensive"
  description: "When electricity is expensive turn off heating"
  trigger:
    - platform: numeric_state
      entity_id: sensor.sd60_electricity_price_percentile
      above: input_number.electricity_price_percentile_limit
  condition: []
  action:
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_upstairs_bathroom
          - climate.heating_downstairs_bathroom
          - climate.heating_living_room
          - climate.heating_utility_room
      data:
        temperature: >
          {{ states('input_number.default_minimum_temperature')|float }}
    - service: notify.devices_to_notify
      data:
        title: "Dyr strøm"
        message: "Varmekabler er skrudd av. Minimum temperatur er {{ states('input_number.default_minimum_temperature')|float }} grader."
  mode: single

#
# Turn off water heater when electricity is expensive
#
- id: "1638626031024"
  alias: "Pricing - Turn off water heater when expensive"
  description: "When electricity is expensive turn water heater off"
  trigger:
    - platform: numeric_state
      entity_id: sensor.sd60_electricity_price_percentile
      above: input_number.electricity_price_percentile_limit
  condition:
    - condition: state
      entity_id: switch.water_heater
      state: "on"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.water_heater

#
# Send notifications when price changes
#
- id: "1638626031022"
  alias: "Pricing - Send notification when price changes"
  description: "When electricity price is updated send a notification"
  trigger:
    - platform: state
      entity_id: sensor.electricity_price
  action:
    - service: notify.devices_to_notify
      data:
        title: "Ny strømpris!"
        message: >
          {{ states.sensor.electricity_price.state }} 
          {{ states.sensor.electricity_price.attributes.unit_of_measurement }}.
          {% if states.sensor.electricity_price.attributes.price_level == "CHEAP" %}
          Dette kaller de BILLIG
          {% elif states.sensor.electricity_price.attributes.price_level == "NORMAL" %}
          Såkalt NORMALT.
          {% elif states.sensor.electricity_price.attributes.price_level == "EXPENSIVE" %}
          Dette er DYRT
          {% elif states.sensor.electricity_price.attributes.price_level == "VERY_EXPENSIVE" %}
          Dette er VELDIG DYRT
          {% else %}
          {{ states.sensor.electricity_price.attributes.price_level }}
          {% endif %}
