#
# Turn off heating when expensive
#
- id: "1638626031020"
  alias: "Heating turn off floor heating when expensive"
  description: "When electricity is expensive turn off heating"
  trigger:
    - platform: state
      entity_id: sensor.electricity_price
      attribute: price_level
      to:
        - EXPENSIVE
        - VERY_EXPENSIVE
  condition: []
  action:
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_upstairs_bathroom
          - climate.heating_downstairs_bathroom
          - climate.heating_living_room
          - climate.heating_utility_room
      data:
        temperature: 16
    - service: notify.devices_to_notify
      data:
        title: "Dyr strøm"
        message: "Varme er skrudd av. Stopp ACER!?!"
  mode: single

#
# Turn on heating when electricity is cheap
#
- id: "1638626031021"
  alias: "Heating turn on floor heating when cheap or normal"
  description: "When electricity is cheap or normal turn heating on when time between 07:00 and 22:00"
  trigger:
    - platform: state
      entity_id: sensor.electricity_price
      attribute: price_level
      to:
        - VERY_CHEAP
        - CHEAP
        - NORMAL
  condition:
    - alias: "Time between 07:00 and 22:00"
      condition: time
      after: "07:00:00"
      before: "22:00:00"
  action:
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_upstairs_bathroom
      data:
        temperature: 26
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_living_room
      data:
        temperature: 19
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_downstairs_bathroom
      data:
        temperature: 24
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_utility_room
      data:
        temperature: 22
    - service: notify.devices_to_notify
      data:
        title: "Billig strøm"
        message: "Varme er skrudd på. Stopp ACER!?!"

  mode: single

#
# Turn on water heater when electricity is cheap
#
- id: "1638626031023"
  alias: "Heating turn on water heater when cheap"
  description: "When electricity is cheap turn water heater on"
  trigger:
    - platform: state
      entity_id: sensor.electricity_price
      attribute: price_level
      to:
        - CHEAP
        - VERY_CHEAP
        - NORMAL
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.water_heater

#
# Turn off water heater when electricity is not cheap
#
- id: "1638626031024"
  alias: "Heating turn off water heater when not cheap"
  description: "When electricity is expensive turn water heater off"
  trigger:
    - platform: state
      entity_id: sensor.electricity_price
      attribute: price_level
      to:
        - EXPENSIVE
        - VERY_EXPENSIVE
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.water_heater

#
# Send notifications when price changes
#
- id: "1638626031022"
  alias: "Send notification when price changes"
  description: "When electricity price is updated send a notification"
  trigger:
    - platform: state
      entity_id: sensor.electricity_price
  action:
    - service: notify.devices_to_notify
      data:
        title: "Ny strømpris!"
        message: >
          {{ states.sensor.electricity_price.state }} 
          {{ states.sensor.electricity_price.attributes.unit_of_measurement }}.
          {% if states.sensor.electricity_price.attributes.price_level == "CHEAP" %}
          Dette kaller de "biLLiG"!?
          {% elif states.sensor.electricity_price.attributes.price_level == "NORMAL" %}
          Såkalt "nOrMaLt!?!!".
          {% elif states.sensor.electricity_price.attributes.price_level == "EXPENSIVE" %}
          Dette er DYRT! Vi blir flådd?!
          {% elif states.sensor.electricity_price.attributes.price_level == "VERY_EXPENSIVE" %}
          ACER presser oss for penger som en sitron!!?
          {% else %}
          {{ states.sensor.electricity_price.attributes.price_level }}
          {% endif %}
