# Time based toggles for heating
#

# At 04:00 floor heating is turned on if price is still cheap
- id: "0400"
  alias: "Heating on at 03:00"
  description: "Turns on floor heating at 03:00 if the price is cheap or normal"
  trigger:
    - platform: time
      at: "03:00:00"
  condition:
    - condition: state
      entity_id: sensor.electricity_price
      attribute: price_level
      state:
        - VERY_CHEAP
        - CHEAP
        - NORMAL
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.water_heater
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_upstairs_bathroom
      data:
        temperature: 30
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_living_room
      data:
        temperature: 20
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_downstairs_bathroom
      data:
        temperature: 28
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_utility_room
      data:
        temperature: 22
    - service: notify.devices_to_notify
      data:
        title: "Varme på!"
        message: "Klokka er 03:00. Strøm er billig. Stopp ACER!?!"
