- id: "1638892111585"
  alias: TV Door - Left Top
  description: When Top Left is pressed cycle bright - medium - dim - off
  trigger:
    - platform: state
      entity_id: switch.tv_door_left
  condition:
    - alias: "make sure the switch is on"
      condition: state
      entity_id: switch.tv_door_left
      state: "on"
  action:
    - service: input_select.select_next
      data:
        cycle: true
      target:
        entity_id: input_select.tv_lights
  mode: single

- id: "1638892111586"
  alias: TV Door - Left Bottom
  description: When Top Left is pressed turn off
  trigger:
    - platform: state
      entity_id: switch.tv_door_left
  condition:
    - alias: "make sure the switch is off"
      condition: state
      entity_id: switch.tv_door_left
      state: "off"
  action:
    - service: input_select.select_last
      target:
        entity_id: input_select.tv_lights
  mode: single

- id: "1638892111587"
  alias: TV Door - Right Top
  description: When Top Right is pressed turn on upstairs and downstairs
  trigger:
    - platform: state
      entity_id: switch.tv_door_right
  condition:
    - alias: "make sure the switch is on"
      condition: state
      entity_id: switch.tv_door_right
      state: "on"
  action:
    - service: input_select.select_first
      target:
        entity_id: input_select.tv_lights
    - service: script.downstairs_all_on_bright
  mode: single

- id: "1638892111588"
  alias: TV Door - Right Bottom
  description: When Bottom Right is pressed turn off upstairs and downstairs
  trigger:
    - platform: state
      entity_id: switch.tv_door_right
  condition:
    - alias: "make sure the switch is on"
      condition: state
      entity_id: switch.tv_door_right
      state: "off"
  action:
    - service: input_select.select_last
      target:
        entity_id: input_select.tv_lights
    - service: script.downstairs_off
  mode: single
