- alias: "TV Lights Mode Change"
  trigger:
    platform: state
    entity_id: input_select.tv_lights
  action:
    - service: >
        {% if is_state("input_select.tv_lights", "Bright") -%}
          script.tv_bright
        {%- elif is_state("input_select.tv_lights", "Medium") -%}
          script.tv_medium_bright
        {%- elif is_state("input_select.tv_lights", "Dimmed") -%}
          script.tv_dimmed
        {%- elif is_state("input_select.tv_lights", "Off") -%}
          script.tv_off
        {%- endif %}

# - service: notify.ios_tmobil_x
#      data:
#        title: 'TV Lights Mode Change'
#        message: >
#          New state is {{ states('input_select.tv_lights') }}
