- id: "1"
  alias: Water Heater On
  description: "Turns water heater on at 13:00"
  trigger:
    - platform: time
      at: "13:00:00"
  condition: []
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.water_heater
  mode: single
