- id: "1638626031020"
  alias: "Toggle heating when expensive"
  description: "When electricity i snot cheap turn off water heater and heating"
  trigger:
    - platform: state
      entity_id: sensor.electricity_price
      attribute: price_level
      from: CHEAP
  condition: []
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.water_heater
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_upstairs_bathroom
          - climate.heating_living_room
          - climate.heating_upstairs_bathroom
          - climate.heating_utility_room
      data:
        temperature: 12
  mode: single

- id: "1638626031021"
  alias: "Toggle heating when cheap"
  description: "When electricity is cheap turn on water heater and heating"
  trigger:
    - platform: state
      entity_id: sensor.electricity_price
      attribute: price_level
      to: CHEAP
  condition: []
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.water_heater
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_upstairs_bathroom
      data:
        temperature: 28
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_living_room
      data:
        temperature: 20
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_downstairs_bathroom
      data:
        temperature: 28
    - service: climate.set_temperature
      target:
        entity_id:
          - climate.heating_utility_room
      data:
        temperature: 22
  mode: single
