# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    language: "no"

recorder:
  purge_keep_days: 31
  db_url: !secret db_url

## spotify:
##   client_id: !secret spotify_client_id
##   client_secret: !secret spotify_client_secret

# Example configuration.yaml entry with manually specified Sonos IP addresses
# sonos:

# influxdb
influxdb:
  api_version: 2
  ssl: false
  host: !secret influxdb_host
  port: !secret influxdb_port
  token: !secret influxdb_token
  organization: !secret influxdb_organization
  bucket: !secret influxdb_bucket
  tags:
    source: hass
  tags_attributes:
    - friendly_name
  exclude:
    entities:
      - zone.home
    domains:
      - persistent_notification
      - person


# -----------------------------------------------------------------------
# Z-Wave
# -----------------------------------------------------------------------
# zwave:
#   usb_path: /dev/ttyACM0
#   network_key: !secret zwave_network_key
#   device_config_glob: !include zwave_device_config_glob.yaml
#   device_config: !include zwave_device_config.yaml
#   debug: false

climate:
  - platform: generic_thermostat
    name: Ovn TV Stue
    unique_id: climateovntvstue
    heater: switch.ovn_tvstue_switch
    target_sensor: sensor.d_upstairs_bathroom_air_temperature
    min_temp: 0
    max_temp: 30
    ac_mode: false
    cold_tolerance: 0.2
    hot_tolerance: 0.2
    min_cycle_duration:
      seconds: 5
    initial_hvac_mode: "heat"
    away_temp: 16
    sleep_temp: 18
    comfort_temp: 21.5
    home_temp: 20
    activity_temp: 19
    precision: 0.1

sensor:
  - platform: openhardwaremonitor
    host: !secret svivel
    port: !secret ohm_port
  - platform: openhardwaremonitor
    host: !secret fraktal
    port: !secret ohm_port

mqtt:
  sensor: !include mqtt/sensors.yaml
  light: !include mqtt/lights.yaml
group: !include_dir_merge_named groups/
automation manual: !include_dir_merge_list automation/
automation ui: !include automations.yaml
template: !include_dir_merge_list templates/
script manual: !include_dir_named scripts/
script ui: !include scripts.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml
notify: !include notify.yaml
