# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    language: "no"

recorder:
  purge_keep_days: 7
  db_url: !secret db_url

## spotify:
##   client_id: !secret spotify_client_id
##   client_secret: !secret spotify_client_secret

# Example configuration.yaml entry with manually specified Sonos IP addresses
# sonos:

# influxdb
influxdb:
  api_version: 2
  ssl: false
  host: !secret influxdb_host
  port: !secret influxdb_port
  token: !secret influxdb_token
  organization: !secret influxdb_organization
  bucket: !secret influxdb_bucket
  tags:
    source: hass
  tags_attributes:
    - friendly_name
  exclude:
    entities:
      - zone.home
    domains:
      - persistent_notification
      - person

# somfy:
#   client_id: !secret somfy_client_id
#   client_secret: !secret somfy_client_secret
# tahoma: !secret tahoma_config

# netatmo
netatmo: !secret netatmo_config

home_connect: !secret home_connect_config

# -----------------------------------------------------------------------
# Z-Wave
# -----------------------------------------------------------------------
# zwave:
#   usb_path: /dev/ttyACM0
#   network_key: !secret zwave_network_key
#   device_config_glob: !include zwave_device_config_glob.yaml
#   device_config: !include zwave_device_config.yaml
#   debug: false

# -----------------------------------------------------------------------
# 433Mhz
# -----------------------------------------------------------------------
# rfxtrx:
#   device: /dev/ttyUSB0
#
# switch:
#   - platform: rfxtrx
#     automatic_add: true
#     devices:
#       0b1100000009965e02010f60:
#         name: "TV Door Left"
#         fire_event: true
#       0b1100020009965e01010f60:
#         name: "TV Door Right"
#         fire_event: true
#       0b1100040009884a02010f60:
#         name: "Garden Door Left"
#         fire_event: true
#       0b1100050009884a01010f60:
#         name: "Garden Door Right"
#         fire_event: true

light: !include_dir_merge_list lights/
mqtt: !include_dir_merge_list mqtt/
group: !include_dir_merge_named groups/
automation manual: !include_dir_merge_list automation/
automation ui: !include automations.yaml
template: !include_dir_merge_list templates/
script manual: !include_dir_named scripts/
script ui: !include scripts.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml
notify: !include notify.yaml
