- id: '1650834902848'
  name: Soverom kveld
  entities:
    light.soverom_alle:
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
      - color_temp
      entity_id:
      - light.bedroom_wardrobe_spots
      - light.bedroom_reading_lights
      - light.bedroom_bokhylle
      - light.bedroom_skrivebord
      icon: mdi:lightbulb-group
      friendly_name: Bedroom all
      supported_features: 40
      color_mode: color_temp
      brightness: 51
      color_temp: 425
      hs_color:
      - 29.294
      - 78.165
      rgb_color:
      - 255
      - 152
      - 55
      xy_color:
      - 0.564
      - 0.389
      state: 'on'
    light.upstairs_bathroom_hallway2:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      supported_color_modes:
      - color_temp
      - hs
      off_brightness:
      friendly_name: Upstairs Bathroom Hallway
      supported_features: 63
      color_mode: color_temp
      brightness: 89
      color_temp: 484
      hs_color:
      - 30.315
      - 91.076
      rgb_color:
      - 255
      - 140
      - 22
      xy_color:
      - 0.592
      - 0.385
      state: 'on'
  icon: mdi:desk-lamp
- id: '1650835170026'
  name: Soverom dag
  entities:
    light.soverom_alle:
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
      - color_temp
      entity_id:
      - light.bedroom_wardrobe_spots
      - light.bedroom_reading_lights
      - light.bedroom_bokhylle
      - light.bedroom_skrivebord
      icon: mdi:lightbulb-group
      friendly_name: Bedroom all
      supported_features: 40
      color_mode: color_temp
      brightness: 254
      color_temp: 350
      hs_color:
      - 28.077
      - 60.925
      rgb_color:
      - 255
      - 172
      - 99
      xy_color:
      - 0.51
      - 0.386
      state: 'on'
    light.upstairs_bathroom_hallway2:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      supported_color_modes:
      - color_temp
      - hs
      off_brightness:
      friendly_name: Upstairs Bathroom Hallway
      supported_features: 63
      color_mode: color_temp
      brightness: 254
      color_temp: 339
      hs_color:
      - 27.911
      - 58.298
      rgb_color:
      - 255
      - 175
      - 106
      xy_color:
      - 0.501
      - 0.384
      state: 'on'
  icon: mdi:weather-sunny
- id: '1650835458215'
  name: Soverom natt
  entities:
    light.soverom_alle:
      min_mireds: 250
      max_mireds: 454
      supported_color_modes:
      - color_temp
      entity_id:
      - light.bedroom_wardrobe_spots
      - light.bedroom_reading_lights
      - light.bedroom_bokhylle
      - light.bedroom_skrivebord
      icon: mdi:lightbulb-group
      friendly_name: Bedroom all
      supported_features: 40
      state: 'off'
    light.upstairs_bathroom_hallway2:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      supported_color_modes:
      - color_temp
      - hs
      off_brightness:
      friendly_name: Upstairs Bathroom Hallway
      supported_features: 63
      state: 'off'
  icon: mdi:moon-waning-crescent
