bedroom_bright:
  alias: Bedroom Bright
  sequence:
  - service: input_select.select_option
    data:
      option: bright
    target:
      entity_id: input_select.bedroom_scenes
  - service: light.turn_on
    data:
      transition: 1
      brightness: 255
    target:
      entity_id: light.bedroom_all_zha_group_0x0004
  - service: light.turn_on
    data:
      color_temp: 360
      brightness: 255
    target:
      entity_id:
      - light.upstairs_bathroom_hallway_light
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: light.turn_on
    data:
      color_temp: 360
    target:
      entity_id: light.bedroom_all_zha_group_0x0004
  mode: single
  icon: mdi:weather-sunny
bedroom_dimmed:
  alias: Bedroom Dimmed
  sequence:
  - service: input_select.select_option
    data:
      option: dimmed
    target:
      entity_id: input_select.bedroom_scenes
  - service: light.turn_on
    data:
      brightness: 25
    target:
      entity_id: light.bedroom_all_zha_group_0x0004
  - service: light.turn_on
    data:
      color_temp: 450
      brightness: 30
    target:
      entity_id:
      - light.upstairs_bathroom_hallway_light
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 100
  - service: light.turn_on
    data:
      color_temp: 425
    target:
      entity_id: light.bedroom_all_zha_group_0x0004
  mode: single
  icon: mdi:moon-waning-crescent
bedroom_off:
  alias: Bedroom Off
  sequence:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.bedroom_all_zha_group_0x0004
  - service: light.turn_on
    data:
      transition: 1
      color_temp: 450
      brightness: 30
    target:
      entity_id:
      - light.upstairs_bathroom_hallway_light
  - service: input_select.select_option
    data:
      option: 'off'
    target:
      entity_id: input_select.bedroom_scenes
  mode: single
  icon: mdi:sleep
utility_room_bright:
  alias: Lights - Utility Room Bright
  sequence:
  - service: light.turn_on
    data:
      color_temp: 360
      brightness: 255
    target:
      entity_id:
      - light.utility_room_zha_group_0x0011
      - light.utility_room_hallway_spots
  mode: single
  icon: mdi:washing-machine
utility_room_off:
  alias: Lights - Utility Room Off
  sequence:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.utility_room_zha_group_0x0011
      - light.utility_room_hallway_spots
  mode: single
  icon: mdi:washing-machine-off
'1700998246768':
  alias: TV Bright
  sequence:
  - service: light.turn_on
    target:
      entity_id:
      - light.tv_bookshelf_spots
      - light.tv_couch
      - light.stairs_zha_group_0x0006
      - light.entrance_zha_group_0x0005
      - light.picture_wall_zha_group_0x000a
    data:
      brightness: 255
      color_temp: 370
  - service: light.turn_on
    target:
      entity_id:
      - light.hue_play_gradient_lightstrip_1
    data:
      brightness: 72
      color_temp: 370
  - service: input_select.select_option
    data:
      entity_id: input_select.tv_lights
      option: Bright
