version: "3.9"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - /home/tm/lib/influxdb/influxdb2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    restart: unless-stopped
