- alias: 'Mode Away'
  trigger:
    platform: state
    entity_id: input_select.home_away
    to: Away
  action:
    - service: notify.ios_tmobil_x
      data:
        title: Home or Away
        message: 'Input set to Away!'
    - service: light.turn_off
      entity_id: group.all_lights
      data:
        transition: 2

- alias: 'Mode Vacation'
  trigger:
    platform: state
    entity_id: input_select.home_away
    to: Vacation
  action:
    - service: notify.ios_tmobil_x
      data:
        title: Home mode Vacation
        message: >
          Input set to Vacation.
          Dining room heating set to 10°C.
          Downstairs bathroom heating set to 20°C.
          Upstairs bathroom heating set to 20°C.
    - service: light.turn_off
      entity_id: group.all_lights
      data:
        transition: 2
    - service: climate.set_temperature
      entity_id: climate.dining_room_heating_heating
      data: 
        temperature: 10
    - service: climate.set_temperature
      entity_id: climate.downstairs_bathroom_heating_heating
      data: 
        temperature: 20
    - service: climate.set_temperature
      entity_id: climate.upstairs_bathroom_heating_heating
      data: 
        temperature: 20

- alias: 'Mode Home'
  trigger:
    platform: state
    entity_id: input_select.home_away
    to: Home
  action:
    - service: notify.ios_tmobil_x
      data:
        title: Home or Away
        message: 'Input set to Home!'