- alias: 'Bedroom - Turn lights on when motion detected'
  trigger:
    - platform: state
      entity_id: sensor.bedroom_sensor_burglar
      from: "0"
      to: "8"
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_sensor_luminance
        below: 40
      - condition: time
        after: '07:00:00'
        before: '22:00:00'
  action:
    - service: light.turn_on
      entity_id:
        - light.bedroom_all_lights
      data_template:
        brightness: >
          {% if is_state('input_select.sd60_mode', 'Night') %}
            64
          {% else %}
            255
          {% endif %}
        kelvin: >
          {% if is_state('input_select.sd60_mode', 'Day') %}
            2700
          {% else %}
            2200
          {% endif %}
        transition: 2

- alias: 'Bedroom - Turn off lights when no motion'
  trigger:
    - platform: state
      entity_id: sensor.bedroom_sensor_burglar
      from: "8"
      to: "0"
      for:
        minutes: 10
  action:
    - service: light.turn_off
      entity_id:
        - light.bedroom_all_lights

