- alias: "Morning - turn on bedroom lights"
  trigger:
    platform: time
    at: '7:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_select.home_away
        state: "Home"
      - condition: sun
        before: sunrise
  action:
    - service: script.bedroom_morning_bright_on
    - service: notify.ios_tmobil_x
      data:
        title: "Morning Bedroom Lights"
        message: "Turning bedroom lights on"
