- alias: "Bedroom - Change radio channel"
  trigger:
    platform: state
    entity_id: input_select.soverom_radio_channels
  action:
    - service: media_player.play_media
      entity_id: media_player.soverom
      data_template:
        media_content_type: "audio/aac"
        media_content_id: >
          {% if is_state('input_select.soverom_radio_channels', 'NRK P1') -%}
            http://nrk-mms-live.telenorcdn.net:80/nrk_radio_p1_ostlandssendingen_aac_h
          {%- elif is_state('input_select.soverom_radio_channels', 'NRK P2') -%}
            http://nrk-mms-live.telenorcdn.net:80/nrk_radio_p2_aac_h
          {%- else -%}
            http://nrk-mms-live.telenorcdn.net:80/nrk_radio_jazz_aac_h
          {%- endif %}
