- alias: "Downstairs door left on"
  trigger:
    platform: mqtt
    topic: /nexa/downstairs/dining_room_left/state
    payload: 'on'
  action:
    - service: light.turn_on
      entity_id: light.paper_1
      data:
        flash: "short"
    - service: script.downstairs_bright 
    - service: notify.ios_tmobil_x
      data:
        title: "Downstairs Switch"
        message: "Door Left ON"

- alias: "Downstairs door left off"
  trigger:
    platform: mqtt
    topic: /nexa/downstairs/dining_room_left/state
    payload: 'off'
  action:
    - service: light.turn_on
      entity_id: light.paper_1
      data:
        flash: "short"
    - service: script.downstairs_off 
    - service: notify.ios_tmobil_x
      data:
        title: "Downstairs Switch"
        message: "Door Left OFF"

- alias: "Downstairs door right on"
  trigger:
    platform: mqtt
    topic: /nexa/downstairs/dining_room_right/state
    payload: 'on'
  action:
    - service: light.turn_on
      entity_id: light.paper_2
      data:
        flash: "short"
    - service: light.turn_on
      entity_id:
        - group.dining_lights
        - group.kitchen_lights
      data:
        transition: 2
    - service: light.turn_on
      entity_id: group.dining_room_hue
      data:
        brightness: 255
        transition: 2
        kelvin: 2700
    - service: notify.ios_tmobil_x
      data:
        title: "Downstairs Switch"
        message: "Door Right ON"

- alias: "Downstairs door right off"
  trigger:
    platform: mqtt
    topic: /nexa/downstairs/dining_room_right/state
    payload: 'off'
  action:
    - service: light.turn_on
      entity_id: light.paper_2
      data:
        flash: "short"
    - service: light.turn_off
      entity_id:
        - group.dining_lights
        - group.kitchen_lights
      data:
        transition: 2
    - service: notify.ios_tmobil_x
      data:
        title: "Downstairs Switch"
        message: "Door Right off"
