- alias: 'Downstairs Luminance - Turning off Lights'
  trigger:
    - platform: numeric_state
      entity_id: sensor.downstairs_sensor_luminance
      above: 200
  condition:
    - condition: state
      entity_id: input_select.sd60_mode
      state: Day
    - condition: state
      entity_id: input_select.home_away
      state: Home
  action:
    - service: light.turn_off
      entity_id:
        - group.downstairs_couch_area
      data:
        transition: 2
    - service: notify.ios_tmobil_x
      data: 
        title: "Turning off downstairs couch area lights"
        message: > 
          Luminance is
          {{ states.sensor.downstairs_sensor_luminance.state_with_unit }}

- alias: 'Downstairs Luminance - Turning on Lights'
  trigger:
    - platform: numeric_state
      entity_id: sensor.downstairs_sensor_luminance
      below: 180
  condition:
    - condition: state
      entity_id: input_select.sd60_mode
      state: Day
    - condition: state
      entity_id: input_select.home_away
      state: Home
  action:
    - service: script.downstairs_couch_area_bright
    - service: notify.ios_tmobil_x
      data: 
        title: "Turning on downstairs couch area lights"
        message: > 
          Luminance is
          {{ states.sensor.downstairs_sensor_luminance.state_with_unit }}