# -----------
# Motion detection in downstairs bathroom
# ------------
- alias: 'Downstairs Bathroom - Turn lights on when motion detected'
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_bathroom_sensor
      from: "off"
      to: "on"
  action: 
    - service: light.turn_on
      entity_id: light.downstairs_bathroom_lights_level
      data:
        brightness: 192
        transition: 1

- alias: 'Downstairs Bathroom - Turn off lights when no motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_bathroom_sensor
      from: "on"
      to: "off"
      for:
        minutes: 10
  action:
    - service: light.turn_off
      entity_id: light.downstairs_bathroom_lights_level
    - service: notify.ios_tmobil_x
      data:
        title: "Downstairs Bathroom"
        message: "No Motion, turning lights off"
