#
# Downstairs Bathroom
- alias: 'Downstairs Bathroom Heating Morning On'
  trigger:
    platform: time
    at: '04:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.home_away
        state: Home
      - condition: numeric_state
        entity_id: sensor.downstairs_bathroom_temperature 
        below: 22
  action:
    - service: climate.set_temperature 
      entity_id: climate.downstairs_bathroom_heating_heating
      data:
        temperature: 25
    - service: notify.ios_tmobil_x
      data:
        title: "Heating Temperature"
        message: >
          Downstairs Bathroom Heating ON. Current temperature
          {{ states.sensor.downstairs_bathroom_heating_temperature.state_with_unit }}
          °C, Goal 25°C

- alias: 'Downstairs Bathroom Heating Morning Off'
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: climate.set_temperature
      entity_id: climate.downstairs_bathroom_heating_heating
      data: 
        temperature: 10
    - service: notify.ios_tmobil_x
      data:
        title: "Downstairs Bathroom Heating"
        message: > 
          Downstairs Bathroom Heating OFF. Current temperature
          {{ states.sensor.downstairs_bathroom_heating_temperature.state_with_unit }}
          , Goal 10°C

- alias: 'Downstairs Bathroom Heating Evening On'
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.home_away
        state: Home
      - condition: numeric_state
        entity_id: sensor.downstairs_bathroom_temperature 
        below: 22
  action:
    - service: climate.set_temperature 
      entity_id: climate.downstairs_bathroom_heating_heating
      data:
        temperature: 25
    - service: notify.ios_tmobil_x
      data:
        title: "Downstairs Bathroom Heating"
        message: > 
          Downstairs Bathroom Heating ON. Current temperature -> 
          {{ states.sensor.downstairs_bathroom_heating_temperature.state_with_unit }}
          , Goal 25°C

- alias: 'Downstairs Bathroom Heating Evening Off'
  trigger:
    - platform: time
      at: '22:00:00'
  action:
    - service: climate.set_temperature
      entity_id: climate.downstairs_bathroom_heating_heating
      data: 
        temperature: 10
    - service: notify.ios_tmobil_x
      data:
        title: "Downstairs Bathroom Heating"
        message: > 
          Downstairs Bathroom Heating OFF. Current temperature 
          {{ states.sensor.downstairs_bathroom_heating_temperature.state_with_unit }}
          , Goal 10°C
