- alias: Front Door Unlocked
  trigger:
    - platform: state
      entity_id: lock.ytterdr
      to: 'unlocked'
  action:
    - service: notify.ios_tmobil_x
      data:
        title: 'Front Door Unlocked'
        message:
          Front door was unlocked by
          {{ states.lock.ytterdr.attributes.changed_by }}