---
# --------------------------------------------------------------------------
# Morning Radio
# --------------------------------------------------------------------------
- alias: "Morning Radio - Start"
  trigger:
    platform: time
    at: "07:15:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_select.home_away
        state: Home
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.nede
        volume_level: 0.3
    - service: input_boolean.turn_off
      entity_id: media_player.play_media
      data:
        entity_id: media_player.nede
        media_content_id: http://nrk-mms-live.telenorcdn.net:80/nrk_radio_p2_aac_h
        media_content_type: "audio/aac"

# --------------------------------------------------------------------------
# Radio P1
# --------------------------------------------------------------------------
- alias: "Radio P1 Pressed - playing"
  trigger:
    platform: state
    entity_id: input_boolean.nede_radio_p1_playing
    from: "on"
    to: "off"
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.nede_radio_p2_playing
        - input_boolean.nede_radio_p3_playing
        - input_boolean.nede_radio_an_playing
        - input_boolean.nede_radio_jazz_playing

# --------------------------------------------------------------------------
# Radio P2
# --------------------------------------------------------------------------
- alias: "Radio P2 Pressed - playing"
  trigger:
    platform: state
    entity_id: input_boolean.nede_radio_p2_playing
    from: "on"
    to: "off"
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.nede_radio_p1_playing
        - input_boolean.nede_radio_p3_playing
        - input_boolean.nede_radio_an_playing
        - input_boolean.nede_radio_jazz_playing

# --------------------------------------------------------------------------
# Radio P3
# --------------------------------------------------------------------------
- alias: "Radio P3 Pressed - playing"
  trigger:
    platform: state
    entity_id: input_boolean.nede_radio_p3_playing
    from: "on"
    to: "off"
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.nede_radio_p1_playing
        - input_boolean.nede_radio_p2_playing
        - input_boolean.nede_radio_an_playing
        - input_boolean.nede_radio_jazz_playing

# --------------------------------------------------------------------------
# Radio Alltid Nyheter
# --------------------------------------------------------------------------
- alias: "Radio Alltid Nyheter Pressed - playing"
  trigger:
    platform: state
    entity_id: input_boolean.nede_radio_an_playing
    from: "on"
    to: "off"
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.nede_radio_p1_playing
        - input_boolean.nede_radio_p2_playing
        - input_boolean.nede_radio_p3_playing
        - input_boolean.nede_radio_jazz_playing

# --------------------------------------------------------------------------
# Radio Jazz
# --------------------------------------------------------------------------
- alias: "Radio Jazz Pressed - playing"
  trigger:
    platform: state
    entity_id: input_boolean.nede_radio_jazz_playing
    from: "on"
    to: "off"
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.nede_radio_p1_playing
        - input_boolean.nede_radio_p2_playing
        - input_boolean.nede_radio_p3_playing
        - input_boolean.nede_radio_an_playing
