# -----------
# Toggle button pressed downstairs
# ------------
# { 
#   topic: "/homeassistant/eventstream"
#   payload: object
#   event_type: "zwave.scene_activated"
#   event_data: {
#     entity_id: "zwave.dining_room_couch_dimmer",
#     node_id: 23,
#     scene_id: 26,
#   }
#   qos: 0,
#   retain: false,
#   _msgid: "e7ceb565.394798"
# }
#
# Second button single click: 26
#               double click: 24
#               triple click: 25
#               hold:         22
#               hold end:     23
- alias: 'Martha - Second Button - Single Click'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.marthas_room
        scene_id: 26
  action:
    - service: light.toggle
      entity_id: light.marthas_bookshelf_all
      data:
        transition: 2

