
- alias: "Morning turn on lights"
  trigger:
    platform: time
    at: '07:20:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_select.home_away
        state: Home
      - condition: numeric_state
        entity_id: sensor.entrance_sensor_luminance
        below: 120
  action:
    - service: light.turn_on
      entity_id:
        - group.upstairs_light
        - group.dining_lights
        - group.kitchen_lights
      data:
        transition: 600
        brightness: 250
        kelvin: 2700
    - service: mqtt.publish
      data:
        topic: 'nexa/dowstairs/dining_room_left/state'
        payload: 'on'
    - service: mqtt.publish
      data:
        topic: 'nexa/dowstairs/dining_room_right/state'
        payload: 'on'
    - service: notify.ios_tmobil_x
      data:
        title: 'Turning on lights'
        message: >
          It's morning. The Luminance is
          {{ states.sensor.entrance_sensor_luminance.state_with_unit }}
          