# ---------------------------------------------------------------------------
# Motion detection in upstairs bathroom
# ---------------------------------------------------------------------------
- alias: 'Upstairs Bathroom - Turn lights on when motion detected'
  trigger:
    - platform: state
      entity_id: sensor.upstairs_bathroom_sensor_burglar
      from: "0"
      to: "8"
  action: 
    - service: light.turn_on
      entity_id: light.dimmer_upstairs_bathroom
      data_template:
        brightness: >
          {% if is_state('input_select.sd60_mode', 'Day') or is_state('input_select.sd60_mode', 'Morning') %}
            240
          {% elif is_state('input_select.sd60_mode', 'Night') %}
            4
          {% else %}
            64
          {% endif %}
        transition: 2

- alias: 'Upstairs Bathroom - Turn off lights when no motion'
  trigger:
    - platform: state
      entity_id: sensor.upstairs_bathroom_sensor_burglar
      from: "8"
      to: "0"
      for:
        minutes: 15
  action:
    - service: light.turn_off
      entity_id: light.dimmer_upstairs_bathroom
