- sensor:
    - name: "power_accumulated_daily_consumption"
      unit_of_measurement: "kWh"
      state: >
        {{'%0.2f'|format(states('sensor.accumulated_consumption')| float) }}

- sensor:
    - name: "power_accumulated_hourly_consumption"
      unit_of_measurement: "kWh"
      state: >
        {{'%0.2f'|format(states('sensor.sd60_kwh_current_hour')| float) }}

- sensor:
    - name: "Electricity Price as Number"
      state: >
        {% set levels = { 'VERY_CHEAP': 0, 'CHEAP': 1, 'NORMAL': 2, 'EXPENSIVE': 3, 'VERY_EXPENSIVE': 4} %}
        {% set level = state_attr('sensor.electricity_price', 'price_level') %}
        {{ levels[level] }}
      attributes:
        level: >
          {{ state_attr('sensor.electricity_price', 'price_level') }}
        state_class: measurement
        device_class: energy

- sensor:
    - name: "Coffeemaker state"
      icon: "mdi:coffee-maker"
      state: >
        {{ states('input_select.coffee_maker_state') }}
